---
apiVersion: v1
kind: Pod
metadata: 
  name: gol-pod
spec: 
  containers:
    - image: saieswarprasad/gameoflife:05-03-2021
      name: my-gol-cont
      resources: 
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"  
      ports:
        - containerPort: 8080
          protocol: TCP
          name: golport
