---
apiVersion: v1
kind: Pod
metadata: 
  name: spc-pod
spec: 
  containers:
    - image: saieswarprasad/springpet-clinic:09-03-2021
      name: my-spc-cont
      resources: 
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"  
      ports:
        - containerPort: 8080
          protocol: TCP
          name: spcport