---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-dev
spec:
  type: NodePort
  selector:
    app: jenkins
    env: dev
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32764  