apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gol-rs
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: gol
      version: "1.0"
  template:
    metadata:
      labels:
        app: gol
        version: "1.0"
    spec:
      containers:
        - image: saieswarprasad/gameoflife:05-03-2021
          name: my-gol-cont
          ports:
            - containerPort: 8080
              name: golport
              protocol: TCP