---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: "2.60.2"
    spec:
      containers:
        - image: jenkins:2.60.2
          name: my-jenkins-cont
          ports:
            - containerPort: 8080
              name: jenkinsport
              protocol: TCP